### PR TITLE
perf: Refactoring extension (total overhaul)

### LINKED ISSUE #172: Does not index typescript modules
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may event implement it and send a PR which would be very appreciated>

#### System information

- OS: Windows 7
- TypeScript Hero version: 0.12.0
- VSCode version: 1.9.1

#### Description

Typescript Hero doesn't index module so it does not recognize when I export a module and try to use it else where

##### Steps to reproduce

1. export a module
```
export module MyModule {
    export const TOTO = 123
}
```
2. Try to use that module in another file
image

<for feature requests, please use the following template>

#### Feature <name>

<description>

#### Reason

<why it would be cool>

### LINKED ISSUE #281: Sorting cannot be disabled
After import group have appeared (typescriptHero.resolver.importGroups) seems that sorting cannot be disabled now. 'typescriptHero.resolver.disableImportsSorting' has no action.

### LINKED ISSUE #303: stringQuoteStyle ignored for import sorting
#### System information

- OS:  Windows 10
- TypeScript Hero version: 1.5.0
- VSCode version: 1.16.1

#### Description
I'm using double quotes:
 "typescriptHero.resolver.stringQuoteStyle": "\""

This quote style works when 

However, when Organizing imports, either using organizeOnSave or the menu:
image

The quotes will always use single quotes. :( I've tried setting the double quotes setting in both my workspace and the individual project file. 

In looking at the unit tests (I couldn't get them to run at all, or I'd have tried to write a failing one) it looks like there's no testing around the quoting style. Something like this...
```

// ImportProxy.test.js
describe('toImport()', () => {
...

  it('should generate a double quoted TsNamedImport', () => {
const options: TypescriptGenerationOptions = {
            eol: ';',
            multiLineWrapThreshold: 120,
            multiLineTrailingComma: false,
            stringQuoteStyle: `"`,
            spaceBraces: true,
            tabSize: 4,
        };

           generator = new TypescriptCodeGenerator(options);

            proxy.addSpecifier('bar');
            proxy.addSpecifier('baz');
            generator.generate(proxy).should.equal(`import { bar, baz } from "foo";`);
        });
});
```

### LINKED ISSUE #310: Spacing inside brackets in the imports after running remove unused imports
#### System information

- OS: Ubuntu
- TypeScript Hero version: 1.5.0 (2017-09-19)
- VSCode version: <version>

#### Description

I enabled the setting for not having spaces inside import braces.

`"typescriptHero.resolver.insertSpaceBeforeAndAfterImportBraces": false`

and running remove unused imports re-introduces the spaces in the braces.

##### Steps to reproduce
1. Get an import without spaces inside braces.
2. Run TSH's remove ununsed imports.

### LINKED ISSUE #341: class auto import not working
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: Win7
- TypeScript Hero version: 1.7.0
- VSCode version: 1.17.2 x64

#### Description

My auto class importing stopped working.
Resolver is showing a little fire in lower left.
Set "typescriptHero.verbosity": "debug"
Log basically shows a message:

First 12 lines of log:
2017-11-08T13:04:59.065Z - info: [DeclarationIndexMapper] initializing index mapper for 1 workspaces
2017-11-08T13:04:59.070Z - info: [DeclarationIndexMapper] initialized
2017-11-08T13:04:59.071Z - info: [ImportResolveExtension] initialized
2017-11-08T13:04:59.072Z - info: [CodeCompletionExtension] initialized
2017-11-08T13:04:59.072Z - info: [DocumentSymbolStructureExtension] initialized
2017-11-08T13:04:59.073Z - info: [CodeActionCreator] initialized
2017-11-08T13:04:59.073Z - info: [OrganizeImportsOnSaveExtension] initialized
2017-11-08T13:04:59.073Z - info: [TypeScriptHero] initialized
2017-11-08T13:05:00.363Z - error: [DeclarationIndexMapper] could not build index for workspace "c:\$USER\WWCT2DEV\wwct2dev", error: TypeError: Cannot read property 'type' of undefined
2017-11-08T13:05:36.567Z - warn: [ImportResolveExtension] index was not ready or not index for this file found
2017-11-08T13:06:46.719Z - info: [DeclarationIndexMapper] rebuilding all indices
2017-11-08T13:06:47.619Z - error: [DeclarationIndexMapper] could not build index for workspace "c:\$USER\WWCT2DEV\wwct2dev", error: TypeError: Cannot read property 'type' of undefined

then it does this for all files I open.
debug: [DeclarationIndexMapper] did not find index for file {"meta":{"file":"~path of any file I open~"}}

### LINKED ISSUE #345: Ignore Errors in Non JS Based Files
#### System information

- OS: Windows
- TypeScript Hero version: 1.7.0
- VSCode version: 

#### Description

SCSS files throw errors on every change. This extension should only work with files that it understands.

##### Steps to reproduce

1. Open a .scss file.
2. Get a message to view the log file.

##### Expected

1. Should use a white list the files to parse so only the files that should be parsed will be.
2. Or consume the error so the message to view the log file does not display with every change to the file.

### LINKED ISSUE #347: Type Hints for Interfaces only showing `interface MyInterface` with no details
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: OSX High Sierra
- TypeScript Hero version: latest
- VSCode version: 1.18.0

#### Description

When hovering over an interface name (ie: "MyInterface") the hint overlay simply shows `interface MyInterface` without detail.

##### Steps to reproduce

1. Create a new Typescript file with the following code
```
interface Foo {
  bar: string
  baz: number
}

const foo: Foo = {
  bar: "bar",
  baz: 2
}
```

2. Hover over the `Foo` in `const foo: Foo`
3. Only `interface Foo` is shown in type hint overlay

I would expect to see the full interface definition instead of just the interface name which isn't very helpful.

### LINKED ISSUE #353: Saving file with TypeScript Hero enabled freezes vim extension
#### System information

- OS: 10.13.1
- TypeScript Hero version: 1.7.0
- VSCode version: 1.18.1

#### Description

When the official Vim extension and TypeScript Hero extension are enabled, saving a file causes the Vim extension to stop responding for 2-4 seconds. After that time, all of the entered keystrokes will be executed, like they had been queued up during that time.

Unsure if this is necessarily a TypeScript Hero problem, but I have disabled all extensions and enabled them one at a time and only TypeScript Hero causes this freezing problem with vim.

##### Steps to reproduce

1. Install TypeScript Hero.
2. Install Vim extension.
3. Edit a TypeScript file and save it.
4. Attempt to enter keystrokes. They will work for a second after saving but then will freeze for a few seconds.

### LINKED ISSUE #361: Multiline imports should respect indentation settings
Related: #74 

#### System information

- OS: Windows 10 x64
- TypeScript Hero version: 1.7.0
- VSCode version: 1.18.1

#### Description

When using the `organize-imports`-command, long imports might be converted to multiline imports.  
However, the multiline imports always use `spaces` as indentation, even if it is set to `tabs`.

##### Steps to reproduce

1. Set indentation to tabs in a `TypeScript`-File
2. Create a long `import`-statement.
3. Use `organize-imports`-command

The multiline import now uses `spaces` instead of `tabs`, the indentation size seems to be respected.

### LINKED ISSUE #363: Crash with Out of Memory
#### System information

- OS: Windows 10
- TypeScript Hero version: 1.8.0
- VSCode version: 1.18.1

#### Description

Typescript Hero crashes after opening project with ~2GB RAM used.

```
info: [TypeScriptHero] initialized
...
debugger inspector at %cFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
%c
<--- Last few GCs --->

[36948:000002651D2B5D30]    83904 ms: Mark-sweep 2052.5 (2134.6) -> 2052.5 (2134.6) MB, 997.6 / 0.0 ms  allocation failure GC in old space requested
[36948:000002651D2B5D30]    84973 ms: Mark-sweep 2052.5 (2134.6) -> 2052.5 (2112.1) MB, 1068.3 / 0.0 ms  last resort 
[36948:000002651D2B5D30]    86107 ms: Mark-sweep 2052.5 (2112.1) -> 2052.5 (2112.1) MB, 1132.2 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000000C477D2B959 <JS Object>
    2: createChildren [C:\Users\User\.vscode\extensions\rbbit.typescript-hero-1.8.0\node_modules\typescript\lib\typescript.js:~94901] [pc=00000393BE2C095A](this=000002FFE5391909 <a NodeObject with map 0000009E70D20449>,sourceFile=000001F2D3182311 <undefined>)
    3: getChildren [C:\Users\User\.vscode\extensions\rbbit.typescript-hero-1.8.0\node_modules\typescript\lib\typescript.js:~94957] [pc=...
Extension host terminated unexpectedly. Code:  3  Signal:  null
Extension host terminated unexpectedly.
```

I'm unsure if the following is related:

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

##### Steps to reproduce

1.  Clone: https://github.com/Silvenga/silvenga.com
2. Checkout `0807516cd93765bedb5a822a20e5453e1b500df4`
3. Open multi-workspace `./workspace.code-workspace`

### LINKED ISSUE #365: Recent update broke autocompletion
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may even implement it and send a PR which would be very appreciated>

#### System information

- OS: Windows 10
- TypeScript Hero version: 1.8
- VSCode version: 1.19

#### Description

Few days ago, the plugin worked perfectly. But with the recent update, autocompletion completely disappeared during typing. I can't automatically import a component or a service in Angular. 

Moreover, I looked inside the log file and it seems OK, no error, only 

> 2017-12-16T15:34:30.049Z - info: [DeclarationIndexMapper] rebuilding all indices
> 2017-12-16T15:34:38.966Z - info: [DeclarationIndexMapper] built index for workspace "project" {"durationMs":8915}

##### Steps to reproduce

1. type the component name
2. No suggestion provided

### LINKED ISSUE #372: extension made vscode unusable (keyboard not responding at all)
#### System information

- OS: linux (ubuntu 17.10)
- TypeScript Hero version: 1.8.0
- VSCode version: 1.19.1

#### Description

Vscode started not responding to any keyboard input while editing a .ts file. I disabled all extensions, reloaded, and it worked again. Proceeded to enable all extensions again, and disable them one by one until I found the culprit. Disabling typescript hero fixed the issue.

I'm not sure how to reproduce exactly, or what specifically in my project or environment makes the extension behave this way... I'm editing a project bundled by parceljs, and don't have a tsconfig.json in the project. Feel free to ask any question that will help figure it out.

### LINKED ISSUE #373: Extension host crash when accessing external function from a js file
#### System information

- OS: macOS High Sierra 10.13.2
- TypeScript Hero version: 1.8
- VSCode version: 1.19.2

#### Description

Started noticing when we had a asp.net core project, we have a site wide site.js file
and is referred to in _layout.cshtml - which is the master layout page

because of certain requirements, site.js had to access a js function that was not defined in site.js but _layout.cshtml ( we can't move that function into site.js because it returns some values form config, which in turn comes from DI framework, which is only accessible in _layout.cshtml )

as soon as I add a function call in site.js that is not defined in site.js , typescript hero causes extension host to crash in 1-2 mins

I've identified typescript hero to be the root cause after process of elimination on all other extensions

extensions list:
DotJoshJohnson.xml
EditorConfig.EditorConfig
GuardRex.status-bar-tasks
alefragnani.Bookmarks
cmlewis89.vscode-togglecodelens
eamodio.gitlens
formulahendry.dotnet-test-explorer
jchannon.csharpextensions
jorgeserrano.vscode-csharp-snippets
k--kato.docomment
minhthai.vscode-todo-parser
ms-vscode.csharp
nwallace.peep
pflannery.vscode-versionlens
qub.qub-xml-vscode
rahulsahay.Csharp-ASPNETCore
rbbit.typescript-hero
reflectiondm.classynaming
ryu1kn.partial-diff
wayou.vscode-todo-highlight 

##### Steps to reproduce

1. asp.net core project
2. site.js referred from _layout.cshtml
3. add a js function to _layout.cshtml
4. call that function form site.js
5. extension host crashes after about a minute, and continues crashing after restarts or window reload

### PR DESCRIPTION
**Pull request by buehler**
- Closes #371
- Closes #361 
- Closes #347

- Fixes #373
- Fixes #372 
- Fixes #365 
- Fixes #363 
- Fixes #353 
- Fixes #345 
- Fixes #341 
- Fixes #310 
- Fixes #303 
- Fixes #310 
- Fixes #281 
- Fixes #172 

#### Description

Whole refactoring of application. Does remove auto importing (since it's in vscode and typescript by default) and disables guessed parsing of files. Will only parse to organize imports now.

This eliminates the memory leaks and enables the extension again. After that, parsing can be added step by step back.

### CODE REVIEW

**Comment by oskarols** [comment]
Thanks a lot for the work you're doing! Really good stuff.

**Comment by stevenmusumeche** [comment]
Thank you!

**Comment by Dante-101** [comment]
Thank you for all the efforts!

**Comment by Zephir77167** [comment]
Thanks, neat! Nice work

**Comment by oskarols** [comment]
Hm. I did not realize all of the commands I was using were removed. Anyone know how one can rollback to 1.8? Can't seem to find any way to generate a vsix from the build commands.

**Comment by oskarols** [comment]
To answer my own question, after a great deal of sleuthing I found the link for the VSIX-file for previous version, which one can use to downgrade to the previous version:
https://rbbit.gallery.vsassets.io/_apis/public/gallery/publisher/rbbit/extension/typescript-hero/1.8.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Comment by buehler** [comment]
I also uploaded those packages from 1.5 upwards.

Those commands will come back, but I need some time to refactor certain parts of the parser.

There is a recursion that kills the GC and memory. So I actually need to refactor to a iterator instead of a recursion. And then I can reenable those features. But maybe I enable the features back but with an opt-in option.

**Comment by oskarols** [comment]
Doesn't look like one can use the uploaded .zip-files to install the extension though. 
No worries about the commands. I just needed them right away -- and I had no issues with memory previously :)

**Comment by buehler** [comment]
@oskarols 
Yea me neither... I assume some guys just indexed their compiled javascript files, which killed the GC.

**Pull request merged**
