### PR TITLE
feat(imports): Add organize on save via workspace hook

### LINKED ISSUE #150: Enable setting to auto organize
<thank you for using and contributing to typescript hero>
<please fill the information below to ease up the process>
<you may event implement it and send a PR which would be very appreciated>

#### System information

- OS: Ubuntu 14.04
- TypeScript Hero version: 0.11.0
- VSCode version: 1.9.0-insider

#### Feature Auto organize

Instead of remembering to add shortcuts, it would be better for users to enable auto organize feature. 
Once enabled, the moment user deletes a reference to a class, the plugin can auto remove corresponding import aswell.

#### Reason

User dont need to remember a shortcut & use this shortcut on each file. Improves his productivity

### PR DESCRIPTION
**Pull request by buehler**
- Closes #150

#### Description

Add an extension part that hooks into the `onWillSaveDocument` hook of vscode
to enable organize on save feature.

### CODE REVIEW

**Comment by buehler** [comment]
I wanna point out a big **thanks** to @zarbuto and @ngfk for pointing me into the right direction of the APIs needed to accomplish this :-)

**Comment by zbarbuto** [comment]
Just tested. Works really well but at the moment for me it's happening after prettier.

This is a problem as typescript hero will, for example, bring all imports onto one line which interferes with my prettier settings for line length wrapping (meaning my lint fails 😢 )

**Comment by zbarbuto** [comment]
FWIW I tried reducing `typescriptHero.resolver.multiLineWrapThreshold` but that didn't seem to work (it still wrapped at the longer length).

**Comment by buehler** [comment]
@zbarbuto well... that's a bummer.

So there are 2 more problems:

### When should I activate the feature?
Default value of the settings is `true` right now. So the feature would run on every installation by default. There are vscode specific settings to this. Should I respect them?
e.g.: The user has `editor.formatOnSave` to false, so I assume he won't be happy when my extension reorders all his imports on save right?

So what could / should be the trigger? A combination of my setting and the editor setting?

### Multi line wrap
That's actually a problem in the parser / generator, I'll have a look at that asap with its own issue ticket.

I did check the APIs of vscode / prettier, my `formatOnSave` logic needs to run as it does right now. Prettier does register a documentFormatProvider, which I can't since I only remove some imports and order them properly. When I register such a provider, I would have to write the formatting logic for the whole document or the formatter would not run.

**Comment by zbarbuto** [comment]
> The user has editor.formatOnSave to false, so I assume he won't be happy when my extension reorders all his imports on save right?

Yeah, I'd say that would be a safe assumption. IMO I would limit it to the condition that the user has `editor.formatOnSave` enable _and_ make it an opt-in feature as `typescriptHero.organiseImportsOnSave`.  If both are true, then the feature can be enabled.

I can understand that TSHero users might want to do their own import formatting but still use `formatOnSave` for another library.

>Multi line wrap

Yeah, it seems strange that it's not respecting the TSHero setting for multi-line wrapping, though. I would have thought if they both had the same line wrapping value it would work as expected but that doesn't seem to be the case 😕 .

**Comment by buehler** [comment]
Alright then :-) I'm going to change the logic before the merge of the feature and then have a look at the mutli-line bug within it's own issue.

Thank you for the suggestions!

**Pull request merged**
