### PR TITLE
Fix/vanishing imports

### LINKED ISSUE #30: Some imports vanish during organize imports
e.g.
`injectable` `Logger` from the parser source

### PR DESCRIPTION
**Pull request by buehler**
Closes #30

### CODE REVIEW

**Comment by buehler** [comment]
@n00dl3 : Would you make a short check with this branch? I checked with various files from the project itself and it seems to be stable.

The next "feature" branch will hopefully contain some integration tests to test this behaviour.

:-)

As soon as you made a short test (if you want to), I'll merge it and depoy the version

**Comment by n00dl3** [comment]
I'm checking this out.

**Comment by buehler** [comment]
They changed something in the workspace logic 😐 
That's why the test fail.

**Comment by n00dl3** [comment]
Still removes `import { X  } from "/foo/bar"` when X is use in `y instanceof X` statement.
Except that, everithing seems allright !

**Comment by buehler** [comment]
Thanks for the help! I'll have a look at that, and the changed workspace logic (I hope you updated your vscode :-) ) and will then have a release

**Comment by n00dl3** [comment]
You're welcome, thank you for all the work ! I'm a bleeding edge guy, of course vs code is updated :wink:  !

**Comment by n00dl3** [comment]
Some other problems :

It seems that the import resolve uses absolute path instead of relative ones.
now I have :
```typescript
import {AppointmentService} from "src/app/commons/dao/appointments/index";
```

instead of
```typescript
import {AppointmentService} from "../../commons/dao/appointments/appointment.service";
```

Plus the import from the picker does not work (displayed but does not import anything).

**Comment by buehler** [comment]
Yep just found out myself, with the new update, they screwed up some promise logic

**Comment by n00dl3** [comment]
being bleeding edge sucks.... :disappointed:

**Comment by n00dl3** [comment]
:tada: Yay ! :tada:

**Comment by buehler** [comment]
Alright... seems like we have a winning commit here :-) 😊

**Pull request merged**
